### ISSUE TITLE
Reset model problem

### ISSUE THREAD

**Issue by max-mykhailenko** [vitalets/checklist-model#14]
When I reset model array in this way
`$scope.checklist = []`

Checkboxes doesn't disappear.

**Comment by Lujaw** [comment]
@lookfirst Thanks

**Comment by ruspaull** [comment]
I had a similar issue myself. My solution was instead of wrapping in another object (like @lookfirst) suggested, you can also access parent scope by using $parent in your ng-model. This is because, ng-repeat creates a child scope of your current scope (the controller scope).

see plunkr: http://plnkr.co/edit/4C5JuSsVHjBufMZzWNzs?p=preview

**Comment by lookfirst** [comment]
@ruspaull Sure, that works in this very specific case, but is kind of avoiding the bigger issue. :wink:  What happens if you're nested within multiple ng-repeats? `$parent.$parent`?!

**Comment by ruspaull** [comment]
@lookfirst Of course, in the bigger picture wrapping inside an object is the way to go. I just wanted to point out why it didn't work in the first case.

**Comment by esharif21** [comment]
if use object it can solved
