### ISSUE TITLE
Model must be wrapped in an object

### ISSUE THREAD

**Issue by asafAzulai** [vitalets/checklist-model#30]
If the "checklist-model" attribute receives a flat list directly from the scope (like this: checklist-model="modelList") - it will be limited: if you clear all from the controller - the UI will not be updated (checks will still be checked). 

I didn't test behaviour of select all.

In order to make it work, the model list must be wrapped in an object, like this:
<input type="checkbox" checklist-model="something.list" ...

and in the controller:
scope.something = {
  list: [1,2,3]
}

**Comment by sazo** [comment]
@asafAzulai 
Thx for pointing this out, this will need to bee express in the docs better.

**Comment by beradrian** [comment]
Clarified in the docs.

**Comment by benams** [comment]
1. I can't find the clarification in the docs.
2. Is this the expected behavior? Should I always wrap my array with a json object if I want to enable the "clear all"? What is the reason?

**Comment by rosston** [comment]
1. It's not the clearest, but it looks like this bit in the docs covers it:
> If you modify directly the value of the `checklist-model`, it is possible that the UI won't be updated. This is because this directive looks for the model in the parent, not in the current scope. Instead of doing `checklistModelList = []` it is better to do `checklistModelList.splice(0, checklistModelList.length)` or wrap it in another object.

2. Yes, this is expected behavior since Angular's scopes use prototypal inheritance. See https://github.com/angular/angular.js/wiki/Understanding-Scopes.

Wrapping your `checklist-model` array in an object will work. You may also use Angular's `controller as` syntax, which [Angular's docs](https://docs.angularjs.org/api/ng/directive/ngController#example) mention the advantages of.
