### ISSUE TITLE
Checklist-Model in Form

### ISSUE THREAD

**Issue by DevQueen** [vitalets/checklist-model#87]
I need to use the Checklist-Model in a form.  I have it working using a get-method in the checklist-model (checklist-model="getServices()").  It works great, but I need to get the selected values into my "form" object like: data-ng-model="form.services".  How can I do this?  Is there an example somewhere that I can look at?  I am working in Asp.Net MVC and need to pass form data back to my MVC controller.  Thanks for your assistance.

**Comment by beradrian** [comment]
I'm not familiar with Asp.Net MVC. But you can try with a series of hidden fields:

    <div ng-repeat="service in getServices()"
        <input type="hidden" name="service" ng-value="service.id">
    </div>

This supposing you don't want to use a variable instead of a function in `checklist-model`. If you'll also add name attribute to the checkbox, the submit will be done automatically.

If this does not work for you, please reopen the issue.
